### ISSUE TITLE
Should demographics table show mean(sd) or age category (frequencies and proportions)? (Demographics script)

### ISSUE THREAD

**Issue by Yewande91** [Yewande91/MaternalImmunisation#14]

**Comment by Yewande91** [comment]
maybe frequency and proportions of age groups better as ages in the analysis are treated as categrical

**Comment by Yewande91** [comment]
run code to see demographics table

**Comment by HorridTom** [comment]
I think frequencies and proportions of age categories for this

**Comment by Yewande91** [comment]
thanks
